require("/Textures/image")

--background images
	image:newImage('blankImage','/Textures/background/blank.png')
	image:newImage('placeholderIcon','/Textures/background/blankSmall.png')
	image:newImage('MainMap','/Textures/background/MapSmall (500).png')
	image:newImage('Stats','/Textures/background/StatsSmall (500).png')
	image:newImage('Inv','/Textures/background/InvSmall (500).png')
	image:newImage('config','/Textures/background/Config (500).png')
	image:newImage('Alert','/Textures/background/Alert (500).png')
	image:newImage('shop_city','/Textures/background/buyinStore (500).png')
	image:newImage('shopnoemp_city','/Textures/background/buyinStore_noEmployee (500).png')
	image:newImage('shophurtemp_city','/Textures/background/buyinStore_hurtEmployee (500).png')
	image:newImage('gameover','/Textures/background/gameover (500).png')
	image:newImage('message','/Textures/background/message (500).png')
	image:newImage('note','/Textures/background/note (500).png')
	image:newImage('MapSelect_City','/Textures/background/MapSelect_City (500).png')
	image:newImage('MapSelect_Desert','/Textures/background/MapSelect_Desert (500).png')
	image:newImage('MapSelect_Ice','/Textures/background/MapSelect_Ice (500).png')
	image:newImage('MapSelect_Swamp','/Textures/background/MapSelect_Swamp (500).png')
	image:newImage('MapSelect_Waste','/Textures/background/MapSelect_Waste (500).png')
	image:newImage('MapSelect_Locations','/Textures/background/Location (500).png')
	image:newImage('city','/Textures/background/City_background (500).png')
	image:newImage('desert','/Textures/background/Desert_background (500).png')
	image:newImage('swamp','/Textures/background/Swamp_background (500).png')
	image:newImage('ice','/Textures/background/IceSpikes_background (500).png')
	image:newImage('waste','/Textures/background/Waste_background (500).png')
	
--icon images
	image:newImage('Selected','/Textures/background/icons/selected.png')
	image:newImage('Hp','/Textures/background/icons/hp.png')
	image:newImage('Tooth','/Textures/background/icons/Tooth.png')
	image:newImage('TraderTooth','/Textures/background/icons/TraderTooth.png')
	image:newImage('Bra','/Textures/background/icons/Ashley\'s Bra.png')
	image:newImage('Mystery','/Textures/background/icons/Mystery.png')